name: project_echopet
services:
  mysql:
    image: mysql:8.0.34
    environment:
      MYSQL_ROOT_PASSWORD: 'root1234'
      MYSQL_DATABASE: 'echopet'
      MYSQL_USER: 'echo'
      MYSQL_PASSWORD: '1234'
    ports:
      - '3306:3306'
    volumes:
      - mysql_volume:/var/lib/mysql
    networks:
      - echo-network

  redis:
    image: redis:latest
    command: redis-server --requirepass 1234
    ports:
      - '6379:6379'
    volumes:
      - redis_volume:/data
    networks:
      - echo-network

  springboot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - '8080:8080'
    networks:
      - echo-network
    depends_on:
      - mysql
      - redis

volumes:
  mysql_volume:
  redis_volume:

networks:
  echo-network: